AllCops:
  TargetRubyVersion: 3.1.2

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 50
  Exclude: 
    - "./lib/football_stats/dao/*.rb"

Metrics/BlockLength:
  Max: 50

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false