/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 08-Oct-2022 4:06:57 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS competition CASCADE
;

DROP TABLE IF EXISTS match CASCADE
;

DROP TABLE IF EXISTS team CASCADE
;

DROP TABLE IF EXISTS team_competition CASCADE
;

/* Create Tables */

CREATE TABLE competition
(
	competition_id integer NOT NULL,
	name varchar(50) NOT NULL,
	code varchar(50) NOT NULL,
	type varchar(50) NOT NULL,
	number_of_available_seasons integer NOT NULL
)
;

CREATE TABLE match
(
	match_id bigint NOT NULL,
	utc_date varchar(50) NOT NULL,
	status varchar(50) NOT NULL,
	matchday integer NOT NULL,
	stage varchar(50) NOT NULL,
	last_updated varchar(50) NOT NULL,
	home_team_id integer NOT NULL,
	away_team_id integer NOT NULL,
	home_half_time integer NULL,
	home_full_time integer NULL,
	away_half_time integer NULL,
	away_full_time integer NULL,
	winner varchar(50) NULL,
	duration varchar(50) NULL
)
;

CREATE TABLE team
(
	team_id integer NOT NULL,
	name varchar(100) NOT NULL
)
;

CREATE TABLE team_competition
(
	team_id integer NOT NULL,
	competition_id integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE competition ADD CONSTRAINT "PK_Competition"
	PRIMARY KEY (competition_id)
;

ALTER TABLE match ADD CONSTRAINT "PK_Match"
	PRIMARY KEY (match_id)
;

CREATE INDEX "IXFK_Match_Team" ON match (home_team_id ASC)
;

CREATE INDEX "IXFK_Match_Team_02" ON match (away_team_id ASC)
;

ALTER TABLE team ADD CONSTRAINT "PK_Team"
	PRIMARY KEY (team_id)
;

ALTER TABLE team_competition ADD CONSTRAINT "PK_team_competition"
	PRIMARY KEY (team_id,competition_id)
;

CREATE INDEX "IXFK_team_competition_competition" ON team_competition (competition_id ASC)
;

CREATE INDEX "IXFK_team_competition_team" ON team_competition (team_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE match ADD CONSTRAINT "FK_Match_Team"
	FOREIGN KEY (home_team_id) REFERENCES team (team_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE match ADD CONSTRAINT "FK_Match_Team_02"
	FOREIGN KEY (away_team_id) REFERENCES team (team_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE team_competition ADD CONSTRAINT "FK_team_competition_competition"
	FOREIGN KEY (competition_id) REFERENCES competition (competition_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE team_competition ADD CONSTRAINT "FK_team_competition_team"
	FOREIGN KEY (team_id) REFERENCES team (team_id) ON DELETE No Action ON UPDATE No Action
;
