/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 02-Oct-2022 6:42:58 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Match" CASCADE
;

DROP TABLE IF EXISTS "Team" CASCADE
;

/* Create Tables */

CREATE TABLE "Match"
(
	match_id bigint NOT NULL,
	utc_date varchar(50) NOT NULL,
	status varchar(50) NOT NULL,
	matchday integer NOT NULL,
	stage varchar(50) NOT NULL,
	last_updated varchar(50) NOT NULL,
	home_team_id integer NOT NULL,
	away_team_id integer NOT NULL,
	home_half_time integer NULL,
	home_full_time integer NULL,
	away_half_time integer NULL,
	away_full_time integer NULL,
	winner varchar(50) NULL,
	duration varchar(50) NULL
)
;

CREATE TABLE "Team"
(
	team_id integer NOT NULL,
	name varchar(100) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Match" ADD CONSTRAINT "PK_Match"
	PRIMARY KEY (match_id)
;

CREATE INDEX "IXFK_Match_Team" ON "Match" (home_team_id ASC)
;

CREATE INDEX "IXFK_Match_Team_02" ON "Match" (away_team_id ASC)
;

ALTER TABLE "Team" ADD CONSTRAINT "PK_Team"
	PRIMARY KEY (team_id)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Match" ADD CONSTRAINT "FK_Match_Team"
	FOREIGN KEY (home_team_id) REFERENCES "Team" (team_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Match" ADD CONSTRAINT "FK_Match_Team_02"
	FOREIGN KEY (away_team_id) REFERENCES "Team" (team_id) ON DELETE No Action ON UPDATE No Action
;